const astronomyObjects = [
  {
    name: "Andromeda Galaxy",
    distanceLightYears: 2.537,
    type: "Galaxy",
    imageURL: "/andromeda.jpg",
    altText: "",
    discoveryYear: 964,
    notableFeatures: "the nearest spiral galaxy to the Milky Way",
  },
  {
    name: "ESO 137-001",
    distanceLightYears: 220000000,
    type: "Galaxy",
    imageURL: "/jelly.jpg",
    altText:
      "Hubble Space Telescope of ESO 137-001, also known as the Jellyfish Galaxy",
    discoveryYear: 2005,
    notableFeatures:
      "One of the most famous jellyfish galaxies (also known as *the* jellyfish galaxy, according to it's wikipedia article). As this galaxy moves to the center of the cluster Abell 3627, it gets stripped away by hot gas, thus creating a 260,000 light-year long tail",
  },
  {
    name: "Sagittarius A*",
    distanceLightYears: 26000,
    type: "Black Hole",
    imageURL: "",
    altText: "",
    discoveryYear: 1974,
    notableFeatures: "Was the first black hole to ever be photographed",
  },
  {
    name: "Crab Nebula",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1758,
    notableFeatures: "Contains a pulsar at its center",
  },
  {
    name: "Sirius",
    distanceLightYears: 8.6,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1844,
    notableFeatures: "Brightest star in the night sky",
  },
  {
    name: "Pillars of Creation",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1995,
    notableFeatures: "Famous Hubble image",
  },
  {
    name: "Vega",
    distanceLightYears: 25,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1850,
    notableFeatures: "fifth brightest in the night sky",
  },
  {
    name: "Messier 87 (M87)",
    distanceLightYears: 53.5,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1781,
    notableFeatures:
      "Home to the first black hole imaged by the Event Horizon Telescope",
  },
  {
    name: "Black Eye Galaxy (M64)",
    distanceLightYears: 17,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1779,
    notableFeatures: "Distinct dark band of dust",
  },
  {
    name: "Great Orion Nebula",
    distanceLightYears: 1344,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1610,
    notableFeatures: "One of the brightest nebulae",
  },
  {
    name: "Proxima Centauri",
    distanceLightYears: 4.24,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1915,
    notableFeatures: "Closest known star to the Sun",
  },
  {
    name: "Whirlpool Galaxy (M51)",
    distanceLightYears: 23,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1773,
    notableFeatures: "Classic spiral structure",
  },
  {
    name: "Ring Nebula (M57)",
    distanceLightYears: 2300,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1779,
    notableFeatures: "Well-known planetary nebula",
  },
  {
    name: "W2246-0526",
    distanceLightYears: 12.4,
    type: "Galaxy",
    imageURL: "/WISE.jpg",
    altText:
      "Artist's impression of the extremely luminous infrared galaxy W2246-0526",
    discoveryYear: 1689,
    notableFeatures:
      "the most luminous known galaxy in the observable universe, 350 trillion times brighter than the sun (it's also cannibalistic! likely the reason why it's so bright)",
  },
  {
    name: "Horsehead Nebula",
    distanceLightYears: 1500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1888,
    notableFeatures: "Iconic shape resembling a horse's head",
  },
  {
    name: "LMC (Large Magellanic Cloud)",
    distanceLightYears: 163,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1519,
    notableFeatures: "Irregular dwarf galaxy",
  },
  {
    name: "Tarantula Nebula",
    distanceLightYears: 161000,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1835,
    notableFeatures: "Contains the most massive known star",
  },
  {
    name: "Helix Nebula",
    distanceLightYears: 650,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1824,
    notableFeatures: "Appears as a giant eye in space",
  },
];

export { astronomyObjects };
