const astronomyObjects = [
  {
    name: "Proxima Centauri",
    distanceLightYears: 4.24,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1915,
    notableFeatures: "Closest known star to the Sun",
  },
  {
    name: "ESO 137-001",
    distanceLightYears: 220000000,
    type: "Galaxy",
    imageURL: "/jelly.jpg",
    altText:
      "Hubble Space Telescope of ESO 137-001, also known as the Jellyfish Galaxy",
    discoveryYear: 2005,
    notableFeatures:
      "One of the most famous jellyfish galaxies (also known as *the* jellyfish galaxy, according to it's wikipedia article). As this galaxy moves to the center of the cluster Abell 3627, it gets stripped away by hot gas, thus creating a 260,000 light-year long tail",
  },
  {
    name: "Horsehead Nebula",
    distanceLightYears: 1500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1888,
    notableFeatures: "Iconic shape resembling a horse's head",
  },
  {
    name: "NGC 4261",
    distanceLightYears: 180000000,
    type: "Black Hole",
    imageURL: "",
    altText: "",
    discoveryYear: 1989,
    notableFeatures:
      "Has large lobes of radio emission extending more than 88,000 light-years",
  },
  {
    name: "W2246-0526",
    distanceLightYears: 12.4,
    type: "Galaxy",
    imageURL: "/WISE.jpg",
    altText:
      "Artist's impression of the extremely luminous infrared galaxy W2246-0526",
    discoveryYear: 1689,
    notableFeatures:
      "the most luminous known galaxy in the observable universe, 350 trillion times brighter than the sun (it's also cannibalistic! likely the reason why it's so bright)",
  },
  {
    name: "Sirius",
    distanceLightYears: 8.6,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1844,
    notableFeatures: "Brightest star in the night sky",
  },
  {
    name: "Boötes Void",
    distanceLightYears: 700000000,
    type: "Void",
    imageURL: "/notquitethevoid.jpg",
    altText:
      "An image of Barnard 68, a dark nebula mistakenly used to refer to the Boötes Void. BUT it looks cool so who cares?",
    discoveryYear: 1981,
    notableFeatures:
      "Colloquially referred to as the Great Nothing, a somewhat spherical region of space found in the vicinity of the constellation Boötes, containing only 60 galaxies instead of the 2,000 that should be expected from an area this large. With a radius of nearly 330 million light years accross, it is one of the largest voids in the visible universe, and is referred to as a supervoid.",
  },
  {
    name: "Veil Nebula",
    distanceLightYears: 1470,
    type: "Nebula",
    imageURL: "/veil.jpg",
    altText:
      "NASA's mosaic of six Hubble pictures of a small area of the Veil Nebula roughly two light-years across, covering only a tiny fraction of the nebula's vast structure.",
    discoveryYear: 1784,
    notableFeatures: "Well-known planetary nebula",
  },
  {
    name: "Black Eye Galaxy (M64)",
    distanceLightYears: 17,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1779,
    notableFeatures: "Distinct dark band of dust",
  },
  {
    name: "Andromeda Galaxy",
    distanceLightYears: 2.537,
    type: "Galaxy",
    imageURL: "/andromeda.jpg",
    altText: "",
    discoveryYear: 964,
    notableFeatures: "the nearest spiral galaxy to the Milky Way",
  },
  {
    name: "Tarantula Nebula",
    distanceLightYears: 161000,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1835,
    notableFeatures: "Contains the most massive known star",
  },
  {
    name: "Sagittarius A*",
    distanceLightYears: 26000,
    type: "Black Hole",
    imageURL: "",
    altText: "",
    discoveryYear: 1974,
    notableFeatures: "Was the first black hole to ever be photographed",
  },
  {
    name: "Vega",
    distanceLightYears: 25,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1850,
    notableFeatures: "fifth brightest in the night sky",
  },
  {
    name: "Whirlpool Galaxy (M51)",
    distanceLightYears: 23,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1773,
    notableFeatures: "Classic spiral structure",
  },
  {
    name: "NGC 3393",
    distanceLightYears: 100000000,
    type: "Black Hole",
    imageURL: "",
    altText: "",
    discoveryYear: 2012,
    notableFeatures:
      "Two black holes at its center, one about 30 million times the mass of the sun and another at least 1 million times the mass of the sun",
  },
  {
    name: "Crab Nebula",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1758,
    notableFeatures: "Contains a pulsar at its center",
  },
  {
    name: "Messier 87 (M87)",
    distanceLightYears: 53.5,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1781,
    notableFeatures:
      "Home to the first black hole imaged by the Event Horizon Telescope",
  },
  {
    name: "Pillars of Creation",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1995,
    notableFeatures: "Famous Hubble image",
  },
  {
    name: "Helix Nebula",
    distanceLightYears: 650,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1824,
    notableFeatures: "Appears as a giant eye in space",
  },
  {
    name: "Great Orion Nebula",
    distanceLightYears: 1344,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1610,
    notableFeatures: "One of the brightest nebulae",
  },
  {
    name: "LMC (Large Magellanic Cloud)",
    distanceLightYears: 163,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1519,
    notableFeatures: "Irregular dwarf galaxy",
  },
];

export { astronomyObjects };
