const astronomyObjects = [
  {
    name: "Andromeda Galaxy",
    distanceLightYears: 2.537,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 965,
    composition: "Stars, gas, and dust",
    notableFeatures: "Nearest spiral galaxy to the Milky Way",
  },
  {
    name: "Betelgeuse",
    distanceLightYears: 642.5,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: Ancient,
    composition: "Red supergiant",
    notableFeatures: "One of the largest stars known",
  },
  {
    name: "Sagittarius A*",
    distanceLightYears: 26000,
    type: "Black Hole",
    imageURL: "",
    altText: "",
    discoveryYear: 1974,
    composition:
      "Incomprehensably condensed matter into a single point in space",
    notableFeatures: "Was the first black hole to ever be photographed",
  },
  {
    name: "Crab Nebula",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1758,
    composition: "Gas and dust from a supernova",
    notableFeatures: "Contains a pulsar at its center",
  },
  {
    name: "Sirius",
    distanceLightYears: 8.6,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: Ancient,
    composition: "Binary star system (Sirius A and B)",
    notableFeatures: "Brightest star in the night sky",
  },
  {
    name: "Pillars of Creation",
    distanceLightYears: 6500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1995,
    composition: "Gas and dust",
    notableFeatures: "Famous Hubble image",
  },
  {
    name: "Vega",
    distanceLightYears: 25,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: Ancient,
    composition: "Main sequence star",
    notableFeatures: "fifth brightest in the night sky",
  },
  {
    name: "Messier 87 (M87)",
    distanceLightYears: 53.5,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1781,
    composition: "Stars, gas, and supermassive black hole",
    notableFeatures:
      "Home to the first black hole imaged by the Event Horizon Telescope",
  },
  {
    name: "Black Eye Galaxy (M64)",
    distanceLightYears: 17,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1779,
    composition: "Stars and dark matter",
    notableFeatures: "Distinct dark band of dust",
  },
  {
    name: "Great Orion Nebula",
    distanceLightYears: 1344,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1610,
    composition: "Gas and dust, young stars",
    notableFeatures: "One of the brightest nebulae",
  },
  {
    name: "Proxima Centauri",
    distanceLightYears: 4.24,
    type: "Star",
    imageURL: "",
    altText: "",
    discoveryYear: 1915,
    composition: "Red dwarf",
    notableFeatures: "Closest known star to the Sun",
  },
  {
    name: "Whirlpool Galaxy (M51)",
    distanceLightYears: 23,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1773,
    composition: "Stars, gas, and dust",
    notableFeatures: "Classic spiral structure",
  },
  {
    name: "Ring Nebula (M57)",
    distanceLightYears: 2300,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1779,
    composition: "Ionized gas",
    notableFeatures: "Well-known planetary nebula",
  },
  {
    name: "Alpha Centauri",
    distanceLightYears: 4.37,
    type: "Star System",
    imageURL: "",
    altText: "",
    discoveryYear: Ancient,
    composition: "Triple star system",
    notableFeatures: "Closest star system to Earth",
  },
  {
    name: "Horsehead Nebula",
    distanceLightYears: 1500,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1888,
    composition: "Dark nebula",
    notableFeatures: "Iconic shape resembling a horse's head",
  },
  {
    name: "LMC (Large Magellanic Cloud)",
    distanceLightYears: 163,
    type: "Galaxy",
    imageURL: "",
    altText: "",
    discoveryYear: 1519,
    composition: "Stars, gas, and dust",
    notableFeatures: "Irregular dwarf galaxy",
  },
  {
    name: "Tarantula Nebula",
    distanceLightYears: 161000,
    type: "Nebula",
    imageURL: "",
    altText: "",
    discoveryYear: 1835,
    composition: "Massive star formation region",
    notableFeatures: "Contains the most massive known star",
  },
  {
    name: "Kepler-186f",
    distanceLightYears: 500,
    type: "Exoplanet",
    imageURL: "",
    altText: "",
    discoveryYear: 2014,
    composition: "Rocky",
    notableFeatures: "First Earth-sized exoplanet in habitable zone",
  },
];

export { astronomyObjects };
